language: ruby
rvm:
  - 2.2.10
  - 2.3.5
  - 2.4.5
  - 2.5.3
  - 2.6.3
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - export BUNDLE_PATH="${TRAVIS_BUILD_DIR}/vendor/bundle"